### ISSUE TITLE
Reports new connection when receiving any traffic

### ISSUE THREAD

**Issue by n1ghtBl00d** [nthdeg/redox#2]
If you hit the port the server is listening on with other traffic, it reports that there is a new connection and prompts you to enter a command. Program hangs after any command is entered.

To recreate:
* Start the server
* run `nmap -sS -sC -p- localhost` in another shell on the host
  * Also works from other machines if you replace `localhost` with the ip address
  * Also works with other tools such as `wget` and `nc` if you specify the port

**Comment by nthdeg** [comment]
Nice, thanks for trying it out, I made the manual easier to read for new users. Best to use the program it came with, I will look into it in the meantime.
